import cmcrameri.cm as cmc
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr
from cycler import cycler
from pyglotaran_extras.plotting.utils import (
    MinorSymLogLocator,
    extract_irf_location,
    shift_time_axis_by_irf_location,
)


def plot_decomposition(result, dataname, wavelength, symlog=True, linthresh=1, xlim = None, ylim = None):
    """
    Processes and plots the decomposition of transient absorption or Time resolved photoluminesence data for a specific wavelength.

    This function decomposes the model into its constituent components (e.g., Coherent Artifact,
    Damped Oscillations, and other kinetic species) and plots their contribution to the
    overall signal at a specific wavelength.

    Parameters
    ----------
    result : pyglotaran.Result
        The result object generated by a pyglotaran optimization/analysis.
    dataname : str
        The identifier of the dataset within the result object to be plotted.
    wavelength : int or float
        The specific wavelength (in nm) to extract and plot the kinetic traces for.

    Returns
    -------
    None
        Displays the plot and saves it as a PNG file.
    """
    # Extract data matrix and CLP (Concentration weighted Linear Parameters)
    matrix = result.data[dataname].matrix
    clp = result.data[dataname].clp

    # Categorize CLP labels to group components logically
    ca_labels = []      # Coherent artifacts
    ca_doas_labels = [] # Coherent artifact damped oscillations
    doas_labels = []    # Standard damped oscillations
    non_doas_labels = [] # Main kinetic species

    for clp_label in matrix.clp_label:
        label_str = clp_label.item()
        if label_str.startswith("coherent_artifact_"):
            ca_labels.append(label_str)
        elif label_str.startswith(("osc5_", "osc6_")):
            ca_doas_labels.append(label_str)
        elif label_str.endswith(("_sin", "_cos")):
            doas_labels.append(label_str)
        else:
            non_doas_labels.append(label_str)

    # Build a dictionary to hold the various data components for plotting
    data_dict = {
        "Data": result.data[dataname].data,
        "Fitted data": result.data[dataname].fitted_data,
    }

    # Add individual non-oscillatory components (species)
    for non_doas_label in non_doas_labels:
        data_dict[non_doas_label] = (
            matrix.sel(clp_label=non_doas_label) * clp.sel(clp_label=non_doas_label)
        ).drop_vars("clp_label")

    # Sum all non-oscillatory components
    data_dict["Without Doas"] = (
        (matrix.sel(clp_label=non_doas_labels)) * clp.sel(clp_label=non_doas_labels)
    ).sum(dim="clp_label")
    
    # Calculate Damped Oscillation contribution (subtracting 1 to center around 0)
    data_dict["Damped Oscillation"] = (
        (matrix.sel(clp_label=doas_labels) - 1) * clp.sel(clp_label=doas_labels)
    ).sum(dim="clp_label")
    
    # Calculate Coherent Artifact contribution
    data_dict["Coherent Artifact"] = (
        matrix.sel(clp_label=ca_labels) * clp.sel(clp_label=ca_labels)
    ).sum(dim="clp_label") + (
        (matrix.sel(clp_label=ca_doas_labels) - 1) * clp.sel(clp_label=ca_doas_labels)
    ).sum(dim="clp_label")

    data = xr.Dataset(data_dict)

    # Plotting configuration
    fig, ax = plt.subplots(figsize=(12, 6))

    # Define a custom color cycle for clear distinction between many components
    myFRLcolors = [
        cmc.batlowS(1, alpha=0.8), "black", "k", "midnightblue", "blue",
        "dodgerblue", "darkred", "olive", "aquamarine", "y", "tab:brown", "tab:purple"
    ]
    ax.set_prop_cycle(cycler(color=myFRLcolors))

    # Plot each component
    for key, data_array in data.data_vars.items():
        # Select data at the nearest available wavelength
        trace = data_array.sel(spectral=wavelength, method="nearest")
        
        # Shift time axis relative to the IRF location (time zero correction)
        irf_location = extract_irf_location(result.data[dataname], wavelength)
        shifted_trace = shift_time_axis_by_irf_location(trace, irf_location=irf_location)
        
        shifted_trace.plot(x="time", ax=ax, label=key)

    # Customize axes
    if xlim: ax.set_xlim(xlim)
    if ylim: ax.set_ylim(ylim)
    if symlog:
        ax.set_xscale("symlog", linthresh=linthresh)
        ax.xaxis.set_minor_locator(MinorSymLogLocator(1e-9))
    
    # Layout legend outside the plot area
    ax.legend(
        bbox_to_anchor=(0, 1.02, 1, 0.2), loc="lower left",
        mode="expand", borderaxespad=0, ncol=4, frameon=False
    )
    
    ax.set_xlabel("Time (ps)")
    ax.set_ylabel("ΔA (mOD)")
    ax.set_title(f"Kinetic Trace at {wavelength} nm")
    ax.set_xlim(xscale)
    
    # Add reference lines for time zero and scale change
    for vline_pos in [0, 10]:
        ax.axvline(vline_pos, color="k", linewidth=1, linestyle='--')

    fig.tight_layout()

    output_filename = f'decomposition_{wavelength}_nm_transparent.png'
    plt.savefig(output_filename, format='png', dpi=600, transparent=True)
    print(f"Plot saved as {output_filename}")
    plt.show()